"""Bundle the local learning site from source curriculum, diagrams and BOM.

No package install, CDN, API or internet connection is needed to use the result.
Use --check to detect stale committed assets without modifying files.
"""
import argparse
import csv
import hashlib
import io
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def outputs():
    paths = {
        "course": "docs/learn-content.json",
        "power": "hardware/wiring/power-map.svg",
        "wiring": "hardware/wiring/connection-map.svg",
        "bom": "hardware/bom.csv",
        "fit": "hardware/cad/generated/bom-fit-report.json",
        "written_bom": "BOM.md",
    }
    raw = {key: (ROOT / path).read_text() for key, path in paths.items()}
    payload = {
        "course": json.loads(raw["course"]),
        "diagrams": {key: raw[key] for key in ("power", "wiring")},
        "bom": list(csv.DictReader(io.StringIO(raw["bom"]))),
        "fit": json.loads(raw["fit"]),
        "source_sha256": {paths[key]: hashlib.sha256((ROOT / path).read_bytes()).hexdigest()
                          for key, path in paths.items()},
    }
    bundle = "// Generated by tools/build_learning.py; edit source files, then rebuild.\n"
    bundle += "window.AUTO_SWITCH_LEARN = " + json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + ";\n"
    return {
        "learn/data.js": bundle,
        "learn/assets/power-map.svg": raw["power"],
        "learn/assets/connection-map.svg": raw["wiring"],
        "learn/assets/bom.csv": raw["bom"],
        "learn/assets/bom-fit-report.json": raw["fit"],
        "learn/assets/BOM.md": raw["written_bom"],
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for relative, content in outputs().items():
        path = ROOT / relative
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(relative)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        raise SystemExit("Stale learning assets: " + ", ".join(stale))
    print("Learning assets are current." if args.check else "Built offline learning site in learn/.")


if __name__ == "__main__":
    main()
